name: Auto Update TheTVApp

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-thetvapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install playwright requests
          playwright install --with-deps firefox

      - name: Extract Encrypted Script
        env:
          ZIP_PASS: ${{ secrets.ZIP_PASS }}
        run: |
          7z x -p"${ZIP_PASS}" -y main.zip

      - name: Run TheTVApp Script
        env:
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: python thetvapp.py
